{% set name = "astartes" %}
{% set version = "1.3.1" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/astartes-{{ version }}.tar.gz
  sha256: 579ee09bf2b47340e1251dcd908db8a227551bed1d60e4f0da1719973157c1e5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - pip
  run:
    - python >={{ python_min }}
    - scikit-learn
    - tabulate
    - numpy
    - scipy
    - pandas

test:
  imports:
    - astartes
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/JacksonBurns/astartes
  summary: Train:Test Algorithmic Sampling for Molecules and Arbitrary Arrays
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JacksonBurns
