{% set name = "astartes" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/astartes-{{ version }}.tar.gz
  sha256: ddad38957f1b2d13d9e4f8ada7cbd1620d91a2c65c28b221994d3ee289b5c5d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64
    - pip
  run:
    - python >=3.8
    - scikit-learn
    - tabulate
    - numpy
    - scipy
    - pandas

test:
  imports:
    - astartes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JacksonBurns/astartes
  summary: Train:Test Algorithmic Sampling for Molecules and Arbitrary Arrays
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JacksonBurns
