{% set name = "astartes" %}
{% set version = "1.3.2" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/astartes-{{ version }}.tar.gz
  sha256: 0383a935bbe10dfcf54d62e63cd26f7180c6e81fc278169db4867f54a8db5a02

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - pip
  run:
    - python >={{ python_min }}
    - scikit-learn
    - tabulate
    - numpy
    - scipy
    - pandas

test:
  imports:
    - astartes
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/JacksonBurns/astartes
  summary: Train:Test Algorithmic Sampling for Molecules and Arbitrary Arrays
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JacksonBurns
