{% set name = "astartes" %}
{% set version = "1.1.3.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/astartes-{{ version }}.tar.gz
  sha256: 06529569011e6bdc1ea8fa21063b1bb62639cb9373c5264c7fd583ace10b071e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=64
    - pip
  run:
    - python >=3.7
    - scikit-learn
    - tabulate
    - numpy
    - scipy
    - pandas

test:
  imports:
    - astartes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JacksonBurns/astartes
  summary: Train:Test Algorithmic Sampling for Molecules and Arbitrary Arrays
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JacksonBurns
