{% set name = "astartes" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/astartes-{{ version }}.tar.gz
  sha256: 920b96e3ad98fd53e4d2781153abed826ae1a2cbca6bd63e956a62620c631e8a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=64
    - pip
  run:
    - python >=3.7
    - scikit-learn
    - tabulate
    - numpy
    - scipy
    - pandas

test:
  imports:
    - astartes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JacksonBurns/astartes
  summary: Train:Test Algorithmic Sampling for Molecules and Arbitrary Arrays
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JacksonBurns
